### ISSUE TITLE
Build fails because of missing files in components directory 

### ISSUE THREAD

**Issue by sanjuchopracool** [sd196821/ESP32-Drone-S3#2]
I am getting following build error when trying to build it.

`-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32s3
CMake Error at /home/educate/esp/esp-idf/tools/cmake/build.cmake:201 (message):
  Failed to resolve component 'i2c_bus'.
Call Stack (most recent call first):
  /home/educate/esp/esp-idf/tools/cmake/build.cmake:227 (__build_resolve_and_add_req)
  /home/educate/esp/esp-idf/tools/cmake/build.cmake:509 (__build_expand_requirements)
  /home/educate/esp/esp-idf/tools/cmake/project.cmake:384 (idf_build_process)
  CMakeLists.txt:18 (project)
`

directory components/driver is missing.
Please add missing files.

**Comment by sd196821** [comment]
Files are added.

**Comment by sanjuchopracool** [comment]
files are still missing in 
/components/drivers/spi_devices/pmw3901

Getting following error

```
CMake Error at /home/educate/esp/esp-idf/tools/cmake/component.cmake:300 (message):
  Include directory
  '/home/educate/DATA/ESP_DRONE/ESP32-Drone-S3/components/drivers/spi_devices/pmw3901/include'
  is not a directory.
Call Stack (most recent call first):
  /home/educate/esp/esp-idf/tools/cmake/component.cmake:473 (__component_add_include_dirs)
  components/drivers/spi_devices/pmw3901/CMakeLists.txt:1 (idf_component_register)
```

**Comment by sd196821** [comment]
3901 added. If more files are missing, please refer to official esp-drone. Because my net are not stable enough when connecting to github, many files may be lost during uploading.

**Comment by sanjuchopracool** [comment]
thanks, its building now.
